version: '3.8'
services:
    tms_fe:
      image: tms_fe
      build:
        context: ./tms_fe
        dockerfile: Dockerfile
      restart: always
      ports:
         - 3000:80
  #      - "443:443"

    tms-be:
      image: tms_be
      build:
        context: ./tms_be
        dockerfile: Dockerfile
      environment:
        - _JAVA_OPTIONS=-Xmx512m -Xms256m
        - SPRING_PROFILES_ACTIVE=dev,api-docs
        - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
        - SPRING_DATASOURCE_URL=jdbc:postgresql://100.126.16.89:5502/postgres
        - SPRING_LIQUIBASE_URL=jdbc:postgresql://100.126.16.89:5502/postgres
        - JHIPSTER_SLEEP=30
      ports:
        - 8080:8080

    nginx:
      image: nginx:stable-alpine
      volumes:
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
      ports: 
        -80:80
      restart: unless-stopped     # or "always"
